- name: vault-token
  emptyDir:
    medium: Memory
- name: config
  configMap:
    name: employernotificationapi-config
    items:
      - key: vault-agent-config.hcl
        path: vault-agent-config.hcl
      - key: consul-template-config.hcl
        path: consul-template-config.hcl
- name: shared-data
  emptyDir: {}
